name: npm

on:
  push:
    paths:
      - package.json
      - .github/workflows/npm.yml

jobs:
  update:
    name: "Node LTS* on ubuntu-latest"
    if: ${{ !contains(github.event.head_commit.message, 'release v') }}

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - run: git config user.email "53265646+charescape@users.noreply.github.com"
      - run: git config user.name  "charescape"

      - run: rm -f package-lock.json
      - run: npm install

      - run: git status

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "package-lock.json"
