name: Tests

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        php: [8.3]

    name: Tests P${{ matrix.php }} - ${{ matrix.os }}

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: dom, mbstring, zip
        coverage: none

    - name: Install Composer dependencies
      run: rm -f composer.lock && composer install --no-interaction --prefer-dist

    - name: Unit Tests
      run: composer test:unit

    - name: Composer Audit
      run: composer audit
